import { FlightInterface} from '../app/flight-interface'

export const FLIGHTS: FlightInterface[] = [{
    id: 12345,
    airlineLogo: 'https://w7.pngwing.com/pngs/254/50/png-transparent-lufthansa-swiss-international-air-lines-airline-heathrow-airport-logo-airline-miscellaneous-logo-miles-more.png',
    airportCode: 'DXB',
    location: ['Office', 'Warehouse'],
    milestoneType: ['Export', 'Import'],
    productCode: 'GCR',
    productGroup: 'N/A',
    DoW: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    openTime1: '08:00',
    closeTime1: '12:00',
    openTime2: '08:00',
    closeTime2: '12:00',
    OPType: 'General',
    validFrom: '10 Nov 2020',
    validTo: '15 Nov 2020',
    nfd: 'No',
    exception: 'N/A'
}, {
    id: 12346,
    airlineLogo: 'https://i.pinimg.com/originals/f5/20/29/f52029d1cffd06f25ec50741bcecd5b3.png',
    airportCode: 'DXB',
    location: ['Office', 'Warehouse', 'Other'],
    milestoneType: ['Export', 'Import', 'Transit'],
    productCode: 'GCR',
    productGroup: 'N/A',
    DoW: ['Sun', 'Mon', 'Tue', 'Wed'],
    openTime1: '08:00',
    closeTime1: '12:00',
    openTime2: '08:00',
    closeTime2: '12:00',
    OPType: 'General',
    validFrom: '10 Nov 2020',
    validTo: '15 Nov 2020',
    nfd: 'No',
    exception: 'N/A'
},
{
    id: 12347,
    airlineLogo: 'https://i.pinimg.com/originals/b8/e7/44/b8e744dbf2e61142b9d74721bab54179.png',
    airportCode: 'DXB',
    location: ['Office', 'Warehouse'],
    milestoneType: ['Export', 'Import', 'Transit'],
    productCode: 'GCR',
    productGroup: 'N/A',
    DoW: ['Sun', 'Mon'],
    openTime1: '08:00',
    closeTime1: '12:00',
    openTime2: '08:00',
    closeTime2: '12:00',
    OPType: 'General',
    validFrom: '10 Nov 2020',
    validTo: '15 Nov 2020',
    nfd: 'No',
    exception: 'N/A'
}]